#!/usr/bin/env python

################################################################################
#
# hist2xsf
#
# Converts an abinit HIST file to an animated XSF file for viewing.
#
################################################################################
#
# Created Jan2012 by Kane O'Donnell (Australian Synchrotron).
#
################################################################################
#
# Copyright 2012 Kane O'Donnell
#
#     This library is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this library.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
# 
# NOTES
#
# 1. To get a HIST output file from abinit, you have to compile it with respect
# to netCDF and enable the trio output to include netcdf.
#
#
################################################################################

import esc_lib
import argparse

parser = argparse.ArgumentParser(description="Convert an Abinit _HIST file to animated XSF.")

parser.add_argument('input', help="Abinit _HIST output file in NetCDF format.")
parser.add_argument('output', help="Name of output XSF file.")

args = parser.parse_args()

crystal = esc_lib.Atoms(args.input, "NetCDF")
crystal.writeXSF(args.output)
