#!/usr/bin/env python
################################################################################
#
# pdb2aims
#
# Converts a .pdb file to FHI-aims geometry.in format. Can optionally choose a 
# filename, otherwise "geometry.in" is used.
#
# Usage: pdb2aims inputfile [-o outputFile]
#
################################################################################
#
# Copyright 2013 Kane O'Donnell
#
#     This library is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this library.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
# 
# NOTES
#
# 1. 
#
################################################################################

from __future__ import division
import argparse
import esc_lib as el

DEBUG=0

parser = argparse.ArgumentParser(description="Convert .pdb to FHI-aims geometry.in")

parser.add_argument('inputfile', help="Input .pdb file.")
parser.add_argument('-o', '--output', default="geometry.in", help="choose a name for your output file.")
args = parser.parse_args()

pdb = el.Atoms(args.inputfile, "pdb")

if pdb.lattice != []:
  pdb.writeAims(args.output, xtype="frac")
else:
  pdb.writeAims(args.output, xtype="ang")